name: flutter_kit
description: A new Flutter package project.
version: 1.0.20
homepage: https://github.com/Sethyrus/flutter_kit

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  collection: any
  easy_localization: ^3.0.7
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^1.0.8
  go_router: ^14.1.1
  graphql: ^5.1.3
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
